version: '2'
services:
    flashme-app:
        image: flashme
        external_links:
            - flashme-postgresql:postgresql
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/flashme
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    flashme-postgresql:
        extends:
            file: postgresql.yml
            service: flashme-postgresql
